# name = input("Enter your name : ")
# print("Welcome ", name)
# val = int(input("Enter any number : "))
# print(type(val),val)
# name = input("Enter your Name : ")
# age = input("Enter your age : ")
# marks = input("Enter the marks you ger : ")
# print("Welcome ",name)
# print("Your age is : ", age)
# print("Conglutation you get : ", marks)